spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: sandeep
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    config:
      customer-url: http://localhost:8222/api/v1/customers
      product-url: http://localhost:8222:/api/v1/products
      payment-url: http://localhost:8222/api/v1/payments

server:
  port: 8070